jobs:
- job: sign_package_macOS_packges
  displayName: Sign Package macOS ${{ parameters.buildArchitecture }}
  condition: succeeded()
  pool:
    type: linux

  variables:
    - name: HOMEBREW_NO_ANALYTICS
      value: 1
    - name: runCodesignValidationInjection
      value: false
    - name: nugetMultiFeedWarnLevel
      value: none
    - name: NugetSecurityAnalysisWarningLevel
      value: none
    - name: skipNugetSecurityAnalysis
      value: true
    - group: DotNetPrivateBuildAccess
    - name: ob_outputDirectory
      value: '$(Build.ArtifactStagingDirectory)/ONEBRANCH_ARTIFACT'
    - name: ob_sdl_binskim_enabled
      value: true
    - name: ob_sdl_credscan_suppressionsfileforartifacts
      value: $(Build.SourcesDirectory)/PowerShell/.config/suppress.json
    - name: BuildArch
      value: ${{ parameters.buildArchitecture }}

  steps:
  - checkout: self
    clean: true

  - pwsh: |
      Get-ChildItem -Path env: | Out-String -width 9999 -Stream | write-Verbose -Verbose
    displayName: Capture environment

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'Current'
      artifact: 'macos-pkgs'
      path: '$(Pipeline.Workspace)'
    displayName: Download MacOs Packages

  - task: onebranch.pipeline.signing@1
    displayName: 'Onebranch Signing MacOS Packages'
    inputs:
      command: 'sign'
      signing_profile: CP-401337-Apple
      files_to_sign: '**/*.{pkg,tar.gz}'
      search_root: '$(Pipeline.Workspace)/macos-pkgs/'
    
  - task: PublishPipelineArtifact@1
    displayName: 'Upload Signed MacOS Packages'
    inputs:
      targetPath: '$(Pipeline.Workspace)/macos-pkgs'
      publishLocation: 'pipeline'
      artifact: 'macos-pkgs-signed'
